import {MODULE_ID} from "../constants.js";
import {currencyOf, currencyToCopper, formatCopper, getMerchantData, isMerchant} from "../utils.js";
import {restockMerchant, setRelation, setTreasury} from "../merchant-service.js";
import {openMerchant} from "./merchant-sheet.js";
import {MerchantWizard} from "./wizard.js";

const AppBase=foundry.appv1.api.Application;
export class MerchantManager extends AppBase{
  static get defaultOptions(){return foundry.utils.mergeObject(super.defaultOptions,{id:"sbs-merchant-manager",title:"SBS Merchant Manager",template:`modules/${MODULE_ID}/templates/manager.html`,width:Math.min(900,Math.max(560,window.innerWidth-360)),height:Math.min(680,Math.max(460,window.innerHeight-120)),resizable:true,minimizable:true,classes:["sbs-merchants","sbsm-manager"],scrollY:[".sbsm-manager-scroll"]});}
  getData(){const rows=[];for(const scene of game.scenes){for(const token of scene.tokens){const d=getMerchantData(token);if(!d)continue;const inv=game.actors.get(d.inventoryActorId);const cp=currencyToCopper(currencyOf(inv));const spendable=d.treasury?.unlimited?Infinity:Math.min(cp,Math.max(0,Number(d.treasury?.maxFundsCp??cp)));rows.push({sceneId:scene.id,tokenId:token.id,name:token.name,scene:scene.name,status:d.status,shop:d.customShopType||d.shopTypeLabel||d.shopType,stock:inv?.items?.size??0,treasury:d.treasury?.unlimited?"∞":formatCopper(spendable),lowMoney:!d.treasury?.unlimited&&spendable<=0,linked:d.tokenMode==="linked",journalId:d.journalId,search:`${token.name} ${scene.name} ${d.shopTypeLabel??d.shopType}`.toLowerCase()});}}const orphans=game.actors.filter(a=>a.getFlag(MODULE_ID,"isInventory")&&!rows.some(r=>getMerchantData(game.scenes.get(r.sceneId)?.tokens.get(r.tokenId))?.inventoryActorId===a.id)).map(a=>({id:a.id,name:a.name}));return{rows,orphans,logo:`modules/${MODULE_ID}/assets/logo.png`};}
  activateListeners(html){super.activateListeners(html);const root=html[0]??html,tokenFor=b=>game.scenes.get(b.dataset.scene)?.tokens.get(b.dataset.token);
    root.querySelector("[data-action='new']")?.addEventListener("click",()=>game.sbsMerchants.create());
    root.querySelectorAll("[data-action='open']").forEach(b=>b.addEventListener("click",()=>openMerchant(tokenFor(b))));root.querySelectorAll("[data-action='edit']").forEach(b=>b.addEventListener("click",()=>new MerchantWizard(tokenFor(b)).render(true)));root.querySelectorAll("[data-action='journal']").forEach(b=>b.addEventListener("click",()=>game.journal.get(b.dataset.journal)?.sheet?.render(true)));
    root.querySelectorAll("[data-action='restock']").forEach(b=>b.addEventListener("click",async()=>{await restockMerchant(tokenFor(b));ui.notifications.info("Merchant restocked.");this.render(true);}));
    root.querySelectorAll("[data-action='locate']").forEach(b=>b.addEventListener("click",async()=>{const scene=game.scenes.get(b.dataset.scene);if(canvas.scene?.id!==scene.id)await scene.view();const t=canvas.tokens.get(b.dataset.token);if(t)canvas.animatePan({x:t.center.x,y:t.center.y,scale:1.5});}));
    root.querySelectorAll("[data-action='treasury']").forEach(b=>b.addEventListener("click",()=>this._treasuryDialog(tokenFor(b))));root.querySelectorAll("[data-action='favor']").forEach(b=>b.addEventListener("click",()=>this._favorDialog(tokenFor(b))));
    root.querySelector("[name='filter']")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();root.querySelectorAll(".sbsm-manager-row").forEach(r=>r.classList.toggle("hidden",!r.dataset.search.includes(q)));});
  }
  _treasuryDialog(token){const d=getMerchantData(token),inv=game.actors.get(d.inventoryActorId),c=currencyOf(inv);new Dialog({title:`Treasury — ${token.name}`,content:`<div class="sbsm-dialog"><div class="sbsm-grid five">${["cp","sp","ep","gp","pp"].map(k=>`<label>${k.toUpperCase()}<input name="${k}" type="number" min="0" value="${c[k]}"></label>`).join("")}</div><label>Maximum buying funds (gp equivalent)<input name="max" type="number" min="0" step="0.01" value="${Number(d.treasury?.maxFundsCp??0)/100}"></label><label class="check"><input name="unlimited" type="checkbox" ${d.treasury?.unlimited?"checked":""}> Unlimited buying funds</label></div>`,buttons:{cancel:{label:"Cancel"},save:{label:"Save",callback:async h=>{const r=h[0]??h;await setTreasury(token,{currency:Object.fromEntries(["cp","sp","ep","gp","pp"].map(k=>[k,Number(r.querySelector(`[name='${k}']`).value)||0])),maxFundsCp:Math.round((Number(r.querySelector("[name='max']").value)||0)*100),unlimited:r.querySelector("[name='unlimited']").checked});this.render(true);}}},default:"save"},{classes:["sbs-merchants","sbsm-dialog-app"],width:600,resizable:true}).render(true);}
  _favorDialog(token){const d=getMerchantData(token),levels=d.favor?.levels??[],actors=game.actors.filter(a=>a.type==="character");const rows=actors.map(a=>{const r=d.favor?.relations?.[a.id]??{};const selectedId=r.favorId!==undefined&&r.favorId!==null?String(r.favorId):String(d.favor?.defaultLevelId??"");return `<div class="sbsm-rel-dialog-row" data-actor="${a.id}"><strong>${a.name}</strong><select name="favor"><option value="" ${selectedId===""?"selected":""}>Merchant Default</option>${levels.map(l=>`<option value="${l.id}" ${selectedId===l.id?"selected":""}>${l.name}</option>`).join("")}</select><input name="sell" type="number" placeholder="Custom player pays %" value="${r.customSellRate??""}"><input name="buy" type="number" placeholder="Custom merchant pays %" value="${r.customBuyRate??""}"></div>`;}).join("");new Dialog({title:`Customer Favor — ${token.name}`,content:`<div class="sbsm-dialog"><p>Character overrides beat the merchant's default rates. Leave custom rates blank to use the selected favor level.</p>${rows}</div>`,buttons:{cancel:{label:"Cancel"},save:{label:"Save Relationships",callback:async h=>{const root=h[0]??h;for(const row of root.querySelectorAll(".sbsm-rel-dialog-row")){const sell=row.querySelector("[name='sell']").value,buy=row.querySelector("[name='buy']").value;await setRelation(token,row.dataset.actor,{favorId:row.querySelector("[name='favor']").value,customSellRate:sell===""?null:Number(sell),customBuyRate:buy===""?null:Number(buy)});}this.render(true);}}},default:"save"},{classes:["sbs-merchants","sbsm-dialog-app"],width:760,resizable:true}).render(true);}
}
