import {COINS, DEFAULT_CONFIG, MERCHANT_STYLES, MODULE_ID, PRESENTATIONS, SHOP_TYPES, SPECIES, TOKEN_COLORS, builtInMerchantImage} from "../constants.js";
import {createMerchant, updateMerchant} from "../merchant-service.js";
import {dropDataFromEvent, resolveDropDocument, stageItem, stageJournal, stageRollTable, stagedItemView} from "../importers.js";
import {deepClone, getMerchantData, itemIdentification, mergeConfig, notifyError, quantityOf} from "../utils.js";
import {chooseMerchantPlacement} from "../placement.js";
import {playMerchantSound} from "../sound.js";

const AppBase=foundry.appv1.api.Application;
const ITEM_TYPES=["weapon","equipment","consumable","tool","loot","container","spell","feat"];

export class MerchantWizard extends AppBase{
  constructor(tokenDoc=null,options={}){super(options);this.tokenDoc=tokenDoc;this.isEdit=Boolean(tokenDoc);this.steps=["basics","token","inventory","pricing","favor","buying","treasury","sound","journal","advanced","summary"];this.activeStep=0;this.config=mergeConfig(DEFAULT_CONFIG,tokenDoc?getMerchantData(tokenDoc):{});this.config.presentation=this.config.presentation||"androgynous";if(!this.config.favor?.defaultLevelId)this.config.favor.defaultLevelId="neutral";if(!this.config.customImage&&(!this.config.tokenImage||/assets\/merchants\/[^/]+-[^/]+\.svg$/i.test(this.config.tokenImage)))this.config.tokenImage=builtInMerchantImage(this.config.species,this.config.merchantStyle,this.config.presentation);this.config.inventory=this.isEdit?[]:deepClone(this.config.inventory??[]);this.selectedLinkUuid=this.config.linkedTokenUuid||"";}
  static get defaultOptions(){return foundry.utils.mergeObject(super.defaultOptions,{id:"sbs-merchant-wizard",title:"Merchant Creator",template:`modules/${MODULE_ID}/templates/wizard.html`,width:Math.min(820,Math.max(520,window.innerWidth-360)),height:Math.min(680,Math.max(480,window.innerHeight-120)),resizable:true,minimizable:true,classes:["sbs-merchants","sbsm-wizard"],scrollY:[".sbsm-wizard-scroll"]});}

  getData(){
    const c=this.config;const characters=game.actors.filter(a=>a.type==="character"&&!a.getFlag(MODULE_ID,"isInventory")&&!a.getFlag(MODULE_ID,"isShell"));
    const relationRows=characters.map(a=>{const r=c.favor?.relations?.[a.id]??{};const selectedId=r.favorId!==undefined&&r.favorId!==null?String(r.favorId):String(c.favor?.defaultLevelId??"");return{id:a.id,name:a.name,favorOptions:[{id:"",name:"Merchant Default",selected:selectedId===""},...(c.favor?.levels??[]).map(l=>({id:l.id,name:l.name,selected:selectedId===l.id}))],customSell:r.customSellRate??"",customBuy:r.customBuyRate??""};});
    const saved=game.settings.get(MODULE_ID,"customMerchantArt")??[];
    return{isEdit:this.isEdit,steps:this.steps.map((id,i)=>({id,label:stepLabel(id),idx:i,active:i===this.activeStep})),config:c,shopTypes:Object.entries(SHOP_TYPES).map(([id,name])=>({id,name,selected:c.shopType===id})),species:Object.entries(SPECIES).map(([id,name])=>({id,name,selected:c.species===id})),presentations:Object.entries(PRESENTATIONS).map(([id,name])=>({id,name,selected:c.presentation===id})),styles:Object.entries(MERCHANT_STYLES).map(([id,name])=>({id,name,selected:c.merchantStyle===id})),colors:Object.entries(TOKEN_COLORS).map(([id,name])=>({id,name,selected:c.tokenColor===id})),inventory:(c.inventory??[]).map((x,i)=>stagedItemView(x,i)),favorLevels:(c.favor?.levels??[]).map((l,i)=>({...l,idx:i,isDefault:l.id===c.favor?.defaultLevelId})),relationRows,itemTypes:ITEM_TYPES.map(id=>({id,checked:(c.buyingRules?.acceptedTypes??[]).includes(id)})),users:game.users.filter(u=>!u.isGM).map(u=>({id:u.id,name:u.name,selected:(c.journal?.selectedUserIds??[]).includes(u.id)})),savedArt:saved.map((x,i)=>({...x,idx:i,selected:c.customImage===x.path})),linkedName:this.selectedLinkUuid?globalThis.fromUuidSync?.(this.selectedLinkUuid)?.name??"Selected token":"No token selected",logo:`modules/${MODULE_ID}/assets/logo.png`,previewImage:c.customImage||c.tokenImage||builtInMerchantImage(c.species,c.merchantStyle,c.presentation),isGM:game.user.isGM};
  }

  activateListeners(html){super.activateListeners(html);const root=html[0]??html;this._populate(root);this._showStep(root);
    root.querySelectorAll(".sbsm-step-tab").forEach(b=>b.addEventListener("click",()=>{this._capture(root);this.activeStep=Number(b.dataset.step);this._showStep(root);}));
    root.querySelector("[data-action='back']")?.addEventListener("click",()=>{this._capture(root);this.activeStep=Math.max(0,this.activeStep-1);this._showStep(root);});
    root.querySelector("[data-action='next']")?.addEventListener("click",()=>{this._capture(root);this.activeStep=Math.min(this.steps.length-1,this.activeStep+1);this._showStep(root);});
    root.querySelector("[data-action='cancel']")?.addEventListener("click",()=>this.close());root.querySelector("[data-action='create']")?.addEventListener("click",()=>this._submit(root));
    for(const name of ["species","presentation","merchantStyle"]){root.querySelector(`[name='${name}']`)?.addEventListener("change",e=>{this._capture(root);if(!this.config.customImage)this.config.tokenImage=builtInMerchantImage(this.config.species,this.config.merchantStyle,this.config.presentation);this.render(true);});}
    root.querySelector("[data-action='pick-image']")?.addEventListener("click",()=>this._pickFile(root,"customImage","image"));root.querySelector("[data-action='pick-sound']")?.addEventListener("click",()=>this._pickFile(root,"sound_path","audio"));root.querySelector("[data-action='preview-sound']")?.addEventListener("click",async()=>{this._capture(root);await playMerchantSound({...this.config,sound:{...this.config.sound,enabled:true,audience:"all"}},game.user,{force:true,notify:true});});
    root.querySelector("[data-action='use-selected-token']")?.addEventListener("click",()=>{const t=canvas.tokens.controlled[0]?.document;if(!t)return ui.notifications.warn("Select one scene token first.");if(t===this.tokenDoc)return ui.notifications.warn("Choose a different token.");this.selectedLinkUuid=t.uuid;this.config.linkedTokenUuid=t.uuid;this.config.tokenMode="linked";this.render(true);});
    root.querySelectorAll("[data-saved-art]").forEach(b=>b.addEventListener("click",()=>{this.config.customImage=b.dataset.savedArt;this.render(true);}));
    root.querySelector("[data-action='clear-custom-image']")?.addEventListener("click",()=>{this.config.customImage="";this.config.tokenImage=builtInMerchantImage(this.config.species,this.config.merchantStyle,this.config.presentation);this.render(true);});
    root.querySelector("[data-action='add-favor']")?.addEventListener("click",()=>{this._capture(root);const id=`favor-${foundry.utils.randomID(6)}`;this.config.favor.levels.push({id,name:"New Favor",sellRate:100,buyRate:60});this.render(true);});
    root.querySelectorAll("[data-remove-favor]").forEach(b=>b.addEventListener("click",()=>{this._capture(root);if(this.config.favor.levels.length<=1)return ui.notifications.warn("Keep at least one favor level.");const idx=Number(b.dataset.removeFavor);const [removed]=this.config.favor.levels.splice(idx,1);if(this.config.favor.defaultLevelId===removed?.id)this.config.favor.defaultLevelId=this.config.favor.levels[0].id;this.render(true);}));
    root.querySelectorAll("[data-remove-stage]").forEach(b=>b.addEventListener("click",()=>{this._capture(root);this.config.inventory.splice(Number(b.dataset.removeStage),1);this.render(true);}));
    root.querySelectorAll("[data-stage-identify]").forEach(b=>b.addEventListener("click",()=>{this._capture(root);const d=this.config.inventory[Number(b.dataset.stageIdentify)];if(d)foundry.utils.setProperty(d,"system.identified",b.dataset.identified==="true");this.render(true);}));
    const dz=root.querySelector(".sbsm-wizard-dropzone");if(dz){dz.addEventListener("dragover",e=>{e.preventDefault();dz.classList.add("dragover");});dz.addEventListener("dragleave",()=>dz.classList.remove("dragover"));dz.addEventListener("drop",e=>this._onDrop(e,root));}
  }

  _populate(root){const c=this.config;set(root,"name",c.name);set(root,"shopType",c.shopType);set(root,"customShopType",c.customShopType);set(root,"description",c.description);set(root,"gmNotes",c.gmNotes);set(root,"status",c.status);set(root,"tokenMode",c.tokenMode);set(root,"species",c.species);set(root,"presentation",c.presentation);set(root,"merchantStyle",c.merchantStyle);set(root,"tokenColor",c.tokenColor);set(root,"customImage",c.customImage);check(root,"saveCustomImage",c.saveCustomImage);set(root,"distance",c.interactionDistance);
    set(root,"sellRate",c.pricing?.sellRate);set(root,"buyRate",c.pricing?.buyRate);set(root,"rounding",c.pricing?.rounding);set(root,"defaultFavor",c.favor?.defaultLevelId);
    check(root,"acceptMagic",c.buyingRules?.acceptMagic);check(root,"acceptMundane",c.buyingRules?.acceptMundane);check(root,"acceptUnidentified",c.buyingRules?.acceptUnidentified);check(root,"acceptZero",c.buyingRules?.acceptZeroValue);check(root,"acceptEquipped",c.buyingRules?.acceptEquipped);set(root,"resellBought",c.buyingRules?.resellBoughtItems);
    for(const coin of COINS)set(root,`treasury_${coin}`,c.treasury?.currency?.[coin]??0);check(root,"treasury_unlimited",c.treasury?.unlimited);set(root,"treasury_max_gp",(Number(c.treasury?.maxFundsCp??0)/100));check(root,"treasury_add_payments",c.treasury?.addCustomerPayments);check(root,"treasury_cap",c.treasury?.capAtMaximum);
    check(root,"sound_enabled",c.sound?.enabled);set(root,"sound_path",c.sound?.path);set(root,"sound_volume",c.sound?.volume);set(root,"sound_audience",c.sound?.audience);set(root,"journal_visibility",c.journal?.visibility);set(root,"restock_mode",c.restock?.mode);set(root,"restock_table",c.restock?.tableUuid);check(root,"restock_treasury",c.restock?.restoreTreasury);
  }

  _capture(root){const val=n=>root.querySelector(`[name='${n}']`)?.value;const bool=n=>Boolean(root.querySelector(`[name='${n}']`)?.checked);this.config.name=val("name")??this.config.name;this.config.shopType=val("shopType")??this.config.shopType;this.config.customShopType=val("customShopType")??"";this.config.description=val("description")??"";this.config.gmNotes=val("gmNotes")??"";this.config.status=val("status")??"open";this.config.tokenMode=val("tokenMode")??this.config.tokenMode;this.config.species=val("species")??this.config.species;this.config.presentation=val("presentation")??this.config.presentation;this.config.merchantStyle=val("merchantStyle")??this.config.merchantStyle;this.config.tokenColor=val("tokenColor")??this.config.tokenColor;this.config.customImage=val("customImage")??this.config.customImage;this.config.saveCustomImage=bool("saveCustomImage");this.config.interactionDistance=Math.max(0,Number(val("distance"))||0);if(!this.config.customImage)this.config.tokenImage=builtInMerchantImage(this.config.species,this.config.merchantStyle,this.config.presentation);
    this.config.pricing={sellRate:Math.max(0,Number(val("sellRate"))||0),buyRate:Math.max(0,Number(val("buyRate"))||0),rounding:val("rounding")||"nearest"};
    const levels=[];root.querySelectorAll(".sbsm-favor-row").forEach(row=>{const idx=Number(row.dataset.idx),old=this.config.favor.levels[idx];if(!old)return;levels.push({...old,name:row.querySelector("[data-favor-name]").value.trim()||old.name,sellRate:Math.max(0,Number(row.querySelector("[data-favor-sell]").value)||0),buyRate:Math.max(0,Number(row.querySelector("[data-favor-buy]").value)||0)});});if(levels.length)this.config.favor.levels=levels;this.config.favor.defaultLevelId=val("defaultFavor")||this.config.favor.levels[0]?.id||"neutral";this.config.favor.relations??={};root.querySelectorAll(".sbsm-relation-row").forEach(row=>{const id=row.dataset.actor;const sell=row.querySelector("[data-rel-sell]").value,buy=row.querySelector("[data-rel-buy]").value;this.config.favor.relations[id]={favorId:row.querySelector("[data-rel-favor]").value,customSellRate:sell===""?null:Number(sell),customBuyRate:buy===""?null:Number(buy)};});
    this.config.buyingRules={acceptedTypes:[...root.querySelectorAll("[name='accepted_type']:checked")].map(x=>x.value),acceptMagic:bool("acceptMagic"),acceptMundane:bool("acceptMundane"),acceptUnidentified:bool("acceptUnidentified"),acceptZeroValue:bool("acceptZero"),acceptEquipped:bool("acceptEquipped"),resellBoughtItems:val("resellBought")||"yes"};
    this.config.treasury??={};this.config.treasury.currency={};for(const coin of COINS)this.config.treasury.currency[coin]=Math.max(0,Number(val(`treasury_${coin}`))||0);this.config.treasury.unlimited=bool("treasury_unlimited");this.config.treasury.maxFundsCp=Math.max(0,Math.round((Number(val("treasury_max_gp"))||0)*100));this.config.treasury.addCustomerPayments=bool("treasury_add_payments");this.config.treasury.capAtMaximum=bool("treasury_cap");
    this.config.sound={enabled:bool("sound_enabled"),path:val("sound_path")||"",volume:Math.max(0,Math.min(1,Number(val("sound_volume"))||0)),audience:val("sound_audience")||"players"};this.config.journal={visibility:val("journal_visibility")||"gm",selectedUserIds:[...root.querySelectorAll("[name='journal_users']:checked")].map(x=>x.value)};this.config.restock={mode:val("restock_mode")||"manual",tableUuid:val("restock_table")||"",restoreTreasury:bool("restock_treasury")};
    root.querySelectorAll(".sbsm-staged-row").forEach(row=>{const idx=Number(row.dataset.idx),d=this.config.inventory[idx];if(!d)return;const stock=d.flags?.[MODULE_ID]?.stock??{};const raw=row.querySelector("[data-stage-qty]").value.trim();stock.infinite=/^x$/i.test(raw);if(!stock.infinite)foundry.utils.setProperty(d,"system.quantity",Math.max(0,Number(raw)||0));stock.visible=row.querySelector("[data-stage-visible]").checked;stock.allowZero=row.querySelector("[data-stage-zero]").checked;d.flags??={};d.flags[MODULE_ID]??={};d.flags[MODULE_ID].stock=stock;});
  }

  _showStep(root){root.querySelectorAll(".sbsm-step-panel").forEach(p=>p.classList.toggle("active",p.dataset.panel===this.steps[this.activeStep]));root.querySelectorAll(".sbsm-step-tab").forEach(t=>t.classList.toggle("active",Number(t.dataset.step)===this.activeStep));const back=root.querySelector("[data-action='back']"),next=root.querySelector("[data-action='next']"),create=root.querySelector("[data-action='create']");if(back)back.disabled=this.activeStep===0;if(next)next.classList.toggle("hidden",this.activeStep===this.steps.length-1);if(create)create.classList.toggle("hidden",this.activeStep!==this.steps.length-1);root.querySelector(".sbsm-wizard-scroll")?.scrollTo({top:0});this._summary(root);}
  _summary(root){const box=root.querySelector(".sbsm-summary");if(!box)return;const c=this.config;box.innerHTML=`<h3>${foundry.utils.escapeHTML(c.name)}</h3><p><strong>Shop:</strong> ${foundry.utils.escapeHTML(c.customShopType||SHOP_TYPES[c.shopType]||c.shopType)}<br><strong>Token:</strong> ${c.tokenMode==="linked"?"Link selected existing token":"Place generated merchant token"}<br><strong>Starting stock entries:</strong> ${(c.inventory??[]).length}<br><strong>Customer rate:</strong> ${c.pricing.sellRate}% · <strong>Buyback:</strong> ${c.pricing.buyRate}%<br><strong>Favor levels:</strong> ${(c.favor?.levels??[]).length}<br><strong>Treasury:</strong> ${c.treasury.unlimited?"Unlimited":`max ${(c.treasury.maxFundsCp/100).toFixed(2)} gp`}<br><strong>Greeting sound:</strong> ${c.sound.enabled?(c.sound.path||"enabled, no file selected"):"Off"}</p>`;}

  async _pickFile(root,name,type){const input=root.querySelector(`[name='${name}']`);if(!input)return;const Picker=globalThis.FilePicker??foundry.applications.apps.FilePicker;try{const p=new Picker({type,current:input.value,callback:path=>{input.value=path;if(name==="customImage")this.config.customImage=path;else this.config.sound.path=path;this.render(true);}});if(p.browse)await p.browse();else p.render?.({force:true});}catch(e){notifyError(e,"Could not open file picker");}}

  async _onDrop(event,root){event.preventDefault();event.stopPropagation();event.currentTarget.classList.remove("dragover");this._capture(root);try{const dd=dropDataFromEvent(event),doc=await resolveDropDocument(dd);if(!doc)throw new Error("Could not resolve that Foundry document.");if(doc.documentName==="Item"){this.config.inventory.push(stageItem(doc,quantityOf(doc),"Wizard drag"));this.render(true);return;}if(["JournalEntry","JournalEntryPage"].includes(doc.documentName)){const staged=await stageJournal(doc,game.user);this.config.inventory.push(...staged.items);for(const coin of COINS)this.config.treasury.currency[coin]=(Number(this.config.treasury.currency[coin])||0)+(Number(staged.currency[coin])||0);ui.notifications.info(`Staged ${staged.items.length} linked item entries from ${staged.sourceName}.`);this.render(true);return;}if(doc.documentName==="RollTable"){return this._tableDialog(doc);}throw new Error("Drop an Item, Journal, Journal Page, or RollTable.");}catch(e){notifyError(e,"Could not stage merchant stock");}}

  async _tableDialog(table){new Dialog({title:`Stage RollTable — ${table.name}`,content:`<div class="sbsm-dialog"><label>Mode<select name="mode"><option value="draw">Draw results</option><option value="all">Add every linked Item result</option></select></label><label>Draw count<input name="count" type="number" min="1" max="100" value="5"></label><p><small>This previews stock without depleting the source RollTable.</small></p></div>`,buttons:{cancel:{label:"Cancel"},stage:{label:"Add to Starting Stock",callback:async h=>{try{const r=h[0]??h,staged=await stageRollTable(table,{mode:r.querySelector("[name='mode']").value,count:Number(r.querySelector("[name='count']").value)||1});this.config.inventory.push(...staged.items);ui.notifications.info(`Staged ${staged.items.length} item result(s) from ${table.name}.`);this.render(true);}catch(e){notifyError(e);}}}},default:"stage"},{classes:["sbs-merchants","sbsm-dialog-app"],width:520,resizable:true}).render(true);}

  async _saveCustomArt(){if(!this.config.saveCustomImage||!this.config.customImage)return;const art=deepClone(game.settings.get(MODULE_ID,"customMerchantArt")??[]);if(!art.some(x=>x.path===this.config.customImage)){art.push({name:this.config.name||"Custom Merchant",path:this.config.customImage});await game.settings.set(MODULE_ID,"customMerchantArt",art.slice(-100));}}
  async _submit(root){this._capture(root);if(!this.config.name.trim())return ui.notifications.warn("Give the merchant a name.");if(this.config.tokenMode==="linked"&&!this.selectedLinkUuid&&!this.isEdit)return ui.notifications.warn("Select an existing token to link, or choose Generated Merchant Token.");try{await this._saveCustomArt();if(this.isEdit){await updateMerchant(this.tokenDoc,this.config);ui.notifications.info("Merchant updated.");await this.close();return;}
      const cfg=deepClone(this.config);await this.close();if(cfg.tokenMode==="linked"){const token=await fromUuid(this.selectedLinkUuid||cfg.linkedTokenUuid);await createMerchant(cfg,{linkToken:token});ui.notifications.info(`${cfg.name} linked as a merchant.`);return;}
      const placement=await chooseMerchantPlacement({name:cfg.name,image:cfg.customImage||cfg.tokenImage});if(!placement)return;await createMerchant(cfg,{scene:game.scenes.get(placement.sceneId),x:placement.x,y:placement.y});ui.notifications.info(`${cfg.name} created.`);
    }catch(e){notifyError(e,this.isEdit?"Could not update merchant":"Could not create merchant");}}
}

function stepLabel(id){return({basics:"Basics",token:"Merchant Token",inventory:"Inventory",pricing:"Pricing",favor:"Favor",buying:"Buying Rules",treasury:"Treasury",sound:"Sound",journal:"Journal",advanced:"Restock",summary:"Create"})[id]??id;}
function set(root,name,value){const e=root.querySelector(`[name='${name}']`);if(e)e.value=value??"";}
function check(root,name,value){const e=root.querySelector(`[name='${name}']`);if(e)e.checked=Boolean(value);}
