import {test} from 'node:test';import assert from 'node:assert/strict';
import {parseSourceBundle,entriesHTML,findSource} from '../scripts/sources.js';
const spell={name:'Test Bolt',source:'SBS',level:1,school:'V',time:[{number:1,unit:'action'}],range:{type:'point',distance:{type:'feet',amount:60}},components:{v:true,s:true},duration:[{type:'instant'}],entries:['Make a ranged spell attack. The target takes {@damage 2d6} fire damage.'],spellAttack:['R'],damageInflict:['fire']};
test('source spell maps native attack, components, slot use, range and damage',()=>{const {records}=parseSourceBundle({spell:[spell]}),s=records[0].data.system,a=Object.values(s.activities)[0];assert.equal(s.school,'evo');assert.equal(s.range.value,60);assert.deepEqual(s.properties,['vocal','somatic']);assert.equal(a.type,'attack');assert.equal(a.damage.parts[0].number,2);assert.equal(a.consumption.spellSlot,true);});
test('source save only deals half on success if that rule is supplied',()=>{for(const half of [false,true]){const r={...spell,spellAttack:[],savingThrow:['dexterity'],entries:[spell.entries[0]+(half?' A successful save takes half as much damage.':'')]};const a=Object.values(parseSourceBundle({spell:[r]}).records[0].data.system.activities)[0];assert.deepEqual(a.save.ability,['dex']);assert.equal(a.damage.onSave,half?'half':'none');}});
test('source cantrip, concentration, ritual and healing use correct native fields',()=>{const r={...spell,level:0,spellAttack:[],damageInflict:[],meta:{ritual:true},duration:[{type:'timed',duration:{type:'minute',amount:1},concentration:true}],entries:['The creature regains {@dice 1d8} hit points.']};const s=parseSourceBundle({spell:[r]}).records[0].data.system;assert.equal(s.activities.sbsSourceAct0001.type,'heal');assert.equal(s.activities.sbsSourceAct0001.consumption.spellSlot,true);assert.ok(s.properties.includes('ritual')&&s.properties.includes('concentration'));});
test('species and background choices become native advancements with generated feature grants',()=>{const {records}=parseSourceBundle({race:[{name:'Test Species',source:'SBS',size:['S','M'],speed:{walk:30},languageProficiencies:[{common:true,choose:{from:['gnomish','elvish'],count:1}}],entries:[{name:'Useful Slime',entries:['Sticky.']}]}],background:[{name:'Test Background',source:'SBS',skillProficiencies:[{arcana:true}],ability:[{choose:{weighted:{from:['int','wis','cha'],weights:[2,1]}}}],entries:[]}]});const race=records.find(r=>r.kind==='race');assert.deepEqual(race.data.system.advancement[0].configuration.sizes,['sm','med']);assert.equal(race.data.system.advancement[1].configuration.choices[0].count,1);assert.ok(race.data.system.advancement.at(-1).configuration.items[0].uuid.startsWith('@forge:'));const bg=records.find(r=>r.kind==='background');assert.equal(bg.data.system.advancement.find(a=>a.type==='AbilityScoreImprovement').configuration.points,3);});
test('class feature references expand into native level-specific grants',()=>{const {records}=parseSourceBundle({class:[{name:'Courier',source:'SBS',hd:{faces:8},classFeatures:['Parcel Ward|Courier|SBS|1|SBS']}],classFeature:[{name:'Parcel Ward',source:'SBS',className:'Courier',level:1,entries:['Custom feature.']}]});const c=records.find(r=>r.kind==='class');assert.equal(c.data.system.hd.denomination,'d8');assert.equal(c.data.system.advancement[0].level,1);assert.equal(c.data.system.advancement[0].configuration.items[0].uuid,'@forge:classFeature:SBS:Courier:SBS:1:Parcel Ward');});
test('monster conversion preserves fractional CR, HP, size, AC and native attack',()=>{const r={name:'Test NPC',source:'SBS',type:'construct',size:['S'],cr:'1/2',hp:{average:12},ac:[{ac:14}],speed:{walk:25},str:14,action:[{name:'Hammer',entries:['{@hit 4} to hit. Hit: {@damage 1d6 + 2} bludgeoning damage.']}]};const d=parseSourceBundle({monster:[r]}).records[0].data;assert.equal(d.system.details.cr,.5);assert.equal(d.system.attributes.ac.flat,14);assert.equal(d.system.traits.size,'sm');assert.equal(d.items[0].system.activities.sbsSourceAct0001.attack.bonus,'4');});
test('ambiguous source names require source selection and unresolved inherited records are explicit',()=>{const r=parseSourceBundle({spell:[spell,{...spell,source:'OTHER'}]}).records;assert.throws(()=>findSource(r,spell.name,'spell'),/Ambiguous/);assert.equal(findSource(r,spell.name,'spell','SBS').flags['sbs-actor-forge'].source,'SBS');assert.throws(()=>parseSourceBundle({monster:[{name:'Copy',_copy:{name:'Base'}}]}),/expanded JSON/);});
test('source entry HTML escapes tags and preserves meaningful 5e.tools labels',()=>{const s=entriesHTML([{name:'<script>',entries:['<img src=x onerror=x> and {@spell Magic Missile|PHB}']}]);assert.ok(!s.includes('<script>')&&!s.includes('<img'));assert.ok(s.includes('Magic Missile'));});
test('same-named features in different classes or levels retain distinct Catalog identities',()=>{const {records}=parseSourceBundle({class:[{name:'Courier',source:'SBS',classFeatures:['Training|Courier|SBS|1|SBS','Training|Courier|SBS|2|SBS']}],classFeature:[{name:'Training',source:'SBS',className:'Courier',level:1,entries:['First level']},{name:'Training',source:'SBS',className:'Courier',level:2,entries:['Second level']},{name:'Training',source:'SBS',className:'Other',level:1,entries:['Other class']}]});const features=records.filter(r=>r.kind==='classFeature');assert.equal(new Set(features.map(r=>r.key)).size,3);const c=records.find(r=>r.kind==='class');assert.notEqual(c.data.system.advancement[0].configuration.items[0].uuid,c.data.system.advancement[1].configuration.items[0].uuid);});
test('inherited records resolve across supplied sources, honor overrides and leave source objects unchanged',()=>{
 const base={name:'Base',source:'BASE',type:'construct',hp:{average:12},ac:[13],speed:{walk:25},action:[]};
 const copy={name:'Courier copy',source:'SBS',_copy:{name:'Base',source:'BASE'},hp:{average:18}};
 const bundle={monster:[copy,base]},before=JSON.stringify(bundle),records=parseSourceBundle(bundle).records;
 const d=records.find(r=>r.name==='Courier copy').data;assert.equal(d.system.attributes.hp.value,18);assert.equal(d.system.attributes.ac.flat,13);assert.equal(d.system.attributes.movement.walk,25);assert.equal(JSON.stringify(bundle),before);
});
test('unsupported copy mods and cycles are explained and never silently flattened',()=>{
 const base={name:'Base',source:'SBS',hp:{average:12}},modified={name:'Modified',source:'SBS',_copy:{name:'Base',source:'SBS',_mod:{hp:[{mode:'unknown'}]}}};
 const r=parseSourceBundle({monster:[base,modified]});assert.equal(r.records.length,1);assert.match(r.warnings[0],/copy modifications/);
 assert.throws(()=>parseSourceBundle({monster:[{name:'A',source:'SBS',_copy:{name:'B',source:'SBS'}},{name:'B',source:'SBS',_copy:{name:'A',source:'SBS'}}]}),/cycle/);
});
test('subclass features become contextual grants at their supplied class levels',()=>{
 const {records}=parseSourceBundle({subclass:[{name:'Dispatch specialist',shortName:'Dispatch',source:'SBS',className:'Courier',classSource:'SBS',subclassFeatures:[['Seal|Courier|SBS|Dispatch|SBS|3|SBS']]}],subclassFeature:[{name:'Seal',source:'SBS',className:'Courier',classSource:'SBS',subclassShortName:'Dispatch',subclassSource:'SBS',level:3,entries:['A feature.']}]});
 const d=records.find(r=>r.kind==='subclass').data;assert.equal(d.system.classIdentifier,'courier');assert.equal(d.system.advancement[0].level,3);assert.ok(d.system.advancement[0].configuration.items[0].uuid.includes('subclassFeature:SBS:Courier:SBS:Dispatch:SBS:3:Seal'));
});
test('source weapons receive a native base damage attack, range and standard properties',()=>{
 const records=parseSourceBundle({item:[{name:'Courier blade',source:'SBS',type:'M',weaponCategory:'martial',dmg1:'1d8',dmg2:'1d10',dmgType:'S',property:['V','R'],bonusWeapon:'+1'},{name:'Dispatch bow',source:'SBS',type:'R',weaponCategory:'simple',dmg1:'1d6',dmgType:'P',range:'80/320',property:['A','2']}] }).records;
 const blade=records[0].data.system,bow=records[1].data.system;
 assert.equal(blade.type.value,'martialM');assert.equal(blade.damage.base.denomination,8);assert.equal(blade.damage.versatile.denomination,10);assert.equal(blade.magicalBonus,1);assert.ok(blade.properties.includes('mgc'));assert.equal(blade.range.reach,10);assert.equal(blade.activities.sbsSourceAct0001.damage.includeBase,true);
 assert.equal(bow.range.value,80);assert.equal(bow.range.long,320);assert.equal(bow.activities.sbsSourceAct0001.attack.type.value,'ranged');
});
