import {MODULE_ID} from "../constants.js";
import {getContainerData} from "../utils.js";
import {isLocked} from "../lock.js";
import {setContainerLocked} from "../container-service.js";
import {openContainer} from "./container-sheet.js";
import {ContainerWizard} from "./wizard.js";
const AppBase=foundry.appv1.api.Application;
export class ContainerManager extends AppBase{
 static get defaultOptions(){return foundry.utils.mergeObject(super.defaultOptions,{id:"sbs-container-manager",title:"Container Manager",template:`modules/${MODULE_ID}/templates/manager.html`,width:Math.max(420,Math.min(900,window.innerWidth-60)),height:Math.max(420,Math.min(700,window.innerHeight-80)),resizable:true,minimizable:true,classes:["sbs-containers","sbs-manager"],scrollY:[".sbs-manager-scroll"]});}
 getData(){const rows=[];for(const scene of game.scenes){for(const token of scene.tokens){const d=getContainerData(token);if(!d)continue;const actor=game.actors.get(d.inventoryActorId);rows.push({sceneId:scene.id,tokenId:token.id,scene:scene.name,name:token.name,state:d.state,locked:isLocked(token),items:actor?.items?.size??0,journalId:d.journalId});}}const orphanActors=game.actors.filter(a=>a.getFlag(MODULE_ID,"isInventory")&&!rows.some(r=>getContainerData(game.scenes.get(r.sceneId)?.tokens.get(r.tokenId))?.inventoryActorId===a.id));return{rows,orphans:orphanActors.map(a=>({id:a.id,name:a.name})),logo:`modules/${MODULE_ID}/assets/logo.svg`};}
 activateListeners(html){super.activateListeners(html);const root=html[0]??html;const find=b=>game.scenes.get(b.dataset.scene)?.tokens.get(b.dataset.token);root.querySelector("[data-action='new']")?.addEventListener("click",()=>game.sbsContainers.create());root.querySelectorAll("[data-action='open']").forEach(b=>b.addEventListener("click",()=>openContainer(find(b))));root.querySelectorAll("[data-action='edit']").forEach(b=>b.addEventListener("click",()=>new ContainerWizard(find(b)).render(true)));root.querySelectorAll("[data-action='toggle-lock']").forEach(b=>b.addEventListener("click",async()=>{const token=find(b);if(!token)return;try{const next=!isLocked(token);await setContainerLocked(token,next,{user:game.user});ui.notifications.info(`${token.name} ${next?"locked":"unlocked"}.`);this.render(true);}catch(err){ui.notifications.error(err?.message??String(err));}}));root.querySelectorAll("[data-action='journal']").forEach(b=>b.addEventListener("click",()=>game.journal.get(b.dataset.journal)?.sheet?.render(true)));root.querySelectorAll("[data-action='locate']").forEach(b=>b.addEventListener("click",async()=>{const scene=game.scenes.get(b.dataset.scene);if(canvas.scene?.id!==scene.id)await scene.view();const t=canvas.tokens.get(b.dataset.token);if(t)canvas.animatePan({x:t.center.x,y:t.center.y,scale:1.5});}));root.querySelector("[name='filter']")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();root.querySelectorAll(".sbs-manager-row").forEach(r=>r.classList.toggle("hidden",!r.dataset.search.includes(q)));});}
}
