import {ID,BUILD,clone,esc,json,sanitize,parseRows,workbookRows,exportRows,makeBook,markItems} from './core.js';
import {ensureLauncher,addSettingsLauncher} from './launcher.js';
import {normalizeOwnership,ownershipChoices,applyOwnershipChoices} from './permissions.js';
import {MODES,CATEGORIES} from './updates.js';
import {preparePlans,previewUpdate,validateImport,importPlans,undoImport} from './engine.js';
import {readPrivateDetails,readUndo,actorRecordKey} from './privacy.js';
import {mountBiography,openBiography} from './biography.js';
import {findActorFolder,folderLabel} from './folders.js';
import {pickPortrait} from './portraits.js';
import {catalogRows} from './sources.js';
import {runNativeAdvancements} from './advancements.js';
import {runCompatibilityChecks} from './selftest.js';
import {destinationEnvironment,destinationChoices,destinationOf} from './destinations.js';
import {readPreferences,savePreset,applyPreset,saveSourceLibrary,loadSourceLibraries,deletePreference,combineSources,validateBundle} from './preferences.js';
import {registerSheetAdapter} from './sheet-adapters.js';
import {saveRowPreset as saveRowPresetUI,managePresets} from './preferences-ui.js';
const D=()=>foundry.applications.api.DialogV2;
let busy=false, sourceRecords=[];const sourceBundles=new Map(),loadedLibraryIds=new Set();
function gm(){if(!game.user.isGM)throw Error('Actor Forge requires a GM.');}
function download(data,name,type='application/json'){const blob=data instanceof Blob?data:new Blob([data],{type});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function report(title,text){return D().wait({window:{title},position:{width:700},content:`<div class="sbs-forge"><pre>${esc(text)}</pre></div>`,buttons:[{action:'ok',label:'Close',default:true}]});}
function env(){
 const kind= k=>({Actor:game.actors,Item:game.items,JournalEntry:game.journal,Folder:game.folders}[k]);
 const base={isGM:game.user.isGM,user:game.user,maxFolderDepth:globalThis.CONST?.FOLDER_MAX_DEPTH ?? 4,randomID:()=>foundry.utils.randomID(),get:(k,id)=>kind(k)?.get ? kind(k).get(id) : kind(k)?.find(x=>x.id===id),list:k=>[...(kind(k) ?? [])],fromUuid:u=>fromUuid(u),
  create:(k,d)=>({Actor:CONFIG.Actor.documentClass,Item:CONFIG.Item.documentClass,JournalEntry:CONFIG.JournalEntry.documentClass,Folder:CONFIG.Folder.documentClass}[k]).create(d,{keepId:true}),
  restore:async(_k,doc,d)=>{await doc.importFromJSON(JSON.stringify(d));return doc;},
  listPacks:()=>[...game.packs],getPack:id=>game.packs.get?.(id) ?? game.packs.find(p=>p.collection===id),
  createInPack:(k,d,pack)=>CONFIG[k].documentClass.create(d,{pack,keepId:true}),
  getSetting:k=>game.settings.get(ID,k),setSetting:(k,v)=>game.settings.set(ID,k,v),
  validateFolder:(d,pack)=>new CONFIG.Folder.documentClass(d,pack?{pack}:{}).validate({strict:true}),validateActor:(d,pack)=>new CONFIG.Actor.documentClass(d,pack?{pack}:{}).validate({strict:true}),validateItem:(d,pack)=>new CONFIG.Item.documentClass(d,pack?{pack}:{}).validate({strict:true}),
  runAdvancements:runNativeAdvancements,
  findItems:async(name,type)=>{const matches=game.items.filter(x=>x.name===name&&(!type||x.type===type));for(const pack of game.packs.filter(x=>x.documentName==='Item')){const idx=await pack.getIndex();for(const x of idx.filter(x=>x.name===name&&(!type||x.type===type)))matches.push({uuid:pack.getUuid(x._id)});}return matches;}
 };
 base.openDestination=value=>destinationEnvironment(base,value);return base;
}
function blankPlan(key,data,extra={}){return {key,row:1,data:markItems(sanitize(data)),errors:[],warnings:[],itemRows:[],selected:true,folder:'',ownership:'',target:'',template:'',relations:[],advancements:[],catalog:[],gmDetails:[],detailsSupplied:false,mode:'merge',advance:false,categories:[...CATEGORIES],...extra};}
async function loadSources(files){
 const pending=new Map(sourceBundles);
 for(const f of files ?? []){const bundle=JSON.parse(await f.text());validateBundle(bundle,f.name);pending.set(f.name,bundle);}
 const result=combineSources(pending);sourceBundles.clear();for(const [name,bundle]of pending)sourceBundles.set(name,bundle);sourceRecords=result.records;return result.warnings;
}
function loadLibraries(ids){const result=loadSourceLibraries(readPreferences(env(),'libraries'),ids,sourceBundles);sourceBundles.clear();for(const [name,bundle]of result.bundles)sourceBundles.set(name,bundle);sourceRecords=result.records;for(const id of ids)loadedLibraryIds.add(id);return result.warnings;}
function packOptions(kind,value=''){const choices=destinationChoices(env(),kind);return `<option value="">${kind==='Actor'?'World actors':'World items'}</option>`+choices.map(p=>`<option value="${esc(p.collection)}" ${p.collection===value?'selected':''}>${esc(p.title)}</option>`).join('')+(value && !choices.some(p=>p.collection===value)?`<option value="${esc(value)}" selected>Unavailable — ${esc(value)} (unlock or choose another collection)</option>`:'');}
function destinationControls(value={}){return `<label>Actor collection<select name="actorPack">${packOptions('Actor',value.actorPack)}</select></label><label>Grant source collection<select name="itemPack">${packOptions('Item',value.itemPack)}</select></label><small>Choose unlocked world compendiums to save reusable templates. Party and vehicle links require World actors. Pack access follows the compendium’s own permissions.</small>`;}
const readDestination=el=>({actorPack:el.querySelector('[name=actorPack]')?.value || '',itemPack:el.querySelector('[name=itemPack]')?.value || ''});
async function importFile(){
 gm();const presets=readPreferences(env(),'presets'),libraries=readPreferences(env(),'libraries');
 const chosen=await D().wait({window:{title:'Actor Forge — Import'},position:{width:700},content:`<div class="sbs-forge"><p>Choose a workbook or exported Foundry actor JSON.</p><label>Saved preset<select name="preset"><option value="">Use workbook settings</option>${presets.entries.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select></label>${destinationControls()}<label>Actor file<input name="file" type="file" accept=".xlsx,.json"></label><label>Optional source files<input name="sources" type="file" accept=".json" multiple></label><details><summary>Saved source libraries</summary>${libraries.entries.map(l=>`<label><input type="checkbox" data-library="${esc(l.id)}"> ${esc(l.name)} · ${l.recordCount} records</label>`).join('') || '<p>Save a library through Sources & Libraries to reuse it here.</p>'}</details><small>${sourceRecords.length} source records already loaded. A selected preset applies its update categories, folder and account choices to every row; review them before import.</small></div>`,render:(_e,d)=>{d.element.querySelector('[name=preset]').addEventListener('change',e=>{const p=presets.entries.find(p=>p.id===e.target.value);d.element.querySelector('[name=actorPack]').value=p?.settings.destination.actorPack ?? '';d.element.querySelector('[name=itemPack]').value=p?.settings.destination.itemPack ?? '';for(const checkbox of d.element.querySelectorAll('[data-library]'))checkbox.checked=p?.settings.libraryIds.includes(checkbox.dataset.library) ?? false;});},buttons:[{action:'read',label:'Validate & Preview',default:true,callback:(_e,_b,d)=>({file:d.element.querySelector('[name=file]').files[0],sources:[...d.element.querySelector('[name=sources]').files],preset:d.element.querySelector('[name=preset]').value,destination:readDestination(d.element),libraryIds:[...d.element.querySelectorAll('[data-library]:checked')].map(el=>el.dataset.library)})}]});if(!chosen?.file)return;
 const preset=presets.entries.find(p=>p.id===chosen.preset);
 if(chosen.preset && !preset)throw Error('This preset is missing. Reopen Import.');
 if(preset)for(const [key,id]of Object.entries(preset.settings.destination))if(id && !destinationChoices(env(),key==='actorPack'?'Actor':'Item').some(p=>p.collection===id))throw Error(`Preset compendium ${id} is missing or locked. Edit the preset or choose Use workbook settings.`);
 const scope=await destinationEnvironment(env(),chosen.destination ?? preset?.settings.destination),libraryIds=chosen.libraryIds ?? preset?.settings.libraryIds ?? [];
 const sourceWarnings=[...loadLibraries(libraryIds),...await loadSources(chosen.sources)],f=chosen.file;let plans;
 if(f.name.toLowerCase().endsWith('.json')){
  const v=JSON.parse(await f.text());
  if(!Array.isArray(v) && !v.type && ['monster','spell','race','background','class','item','feat'].some(k=>Array.isArray(v[k]))){await loadSources([f]);return sourcePicker(scope,preset);}
  const arr=Array.isArray(v)?v:[v];plans=arr.map((data,i)=>blankPlan(data.flags?.[ID]?.key || `json-${i}`,data,{sourceActorId:data._id,detailsSupplied:true,ownership:JSON.stringify(data.ownership ?? {})}));
 }else plans=parseRows(workbookRows(XLSX,XLSX.read(await f.arrayBuffer(),{type:'array'})));
 for(const p of plans){p.catalog.push(...catalogRows(sourceRecords));p.warnings.push(...sourceWarnings);}
 if(preset)applyPreset(plans,preset,game.users);
 await preparePlans(plans,scope,sourceRecords);await preview(plans,scope);
}
const ACCESS=[[0,'None'],[1,'Limited — basic information'],[2,'Observer — view sheet'],[3,'Owner — control actor']];
function levelOptions(value,inherit=false){return (inherit?`<option value="-1" ${value===-1?'selected':''}>Use default access</option>`:'')+ACCESS.map(([n,label])=>`<option value="${n}" ${n===value?'selected':''}>${esc(label)}</option>`).join('');}
function permissionControls(p){p.permissionBase=normalizeOwnership(p.ownership || p.data.ownership || '');return `<details class="account-permissions"><summary>Player account access</summary><label>Default player access<select name="access-default">${levelOptions(p.permissionBase.default)}</select></label>${ownershipChoices(p.permissionBase,game.users).map(u=>`<label>${esc(u.name)}<select data-access-user="${esc(u.id)}">${levelOptions(u.level,true)}</select></label>`).join('')}${![...game.users].some(u=>!u.isGM)?'<p>No player accounts in this world yet.</p>':''}<small>GM accounts always have full access. On updates, enable Permissions below to apply these choices.</small></details>`;}
function updateChoices(p,scope){return '<option value="">Create a new actor</option>'+scope.list('Actor').sort((a,b)=>a.name.localeCompare(b.name)).map(a=>`<option value="${esc(a.id)}" ${a.id===p.target?'selected':''}>${esc(a.name)} (${esc(a.type)})</option>`).join('')+(p.target&&!scope.get('Actor',p.target)?`<option value="${esc(p.target)}" selected>Missing workbook target: ${esc(p.target)}</option>`:'');}
const CATEGORY_NAMES={fields:'Stats, name, portrait & folder',items:'Items, spells & features',effects:'Active effects',details:'SBS Details',relationships:'Group & vehicle links',token:'Token settings',permissions:'Permissions'};
function readRow(tr,p){
 const data=clone(p.data);data.name=tr.querySelector('[name=name]').value.trim();data.type=tr.querySelector('[name=type]').value;data.img=tr.querySelector('[name=image]').value || p.data.img || 'icons/svg/mystery-man.svg';data.folder=tr.querySelector('[name=folder]').value || null;
 data.ownership=applyOwnershipChoices(p.permissionBase,tr.querySelector('[name=access-default]').value,[...tr.querySelectorAll('[data-access-user]')].map(el=>({id:el.dataset.accessUser,level:el.value})));
 return {...p,data,folderPath:tr.querySelector('[name=folderPath]').value,conflictChoices:{...p.conflictChoices,...Object.fromEntries([...tr.querySelectorAll('[data-conflict-choice]')].map(el=>[el.dataset.conflictChoice,el.value]))},target:tr.querySelector('[name=target]').value,mode:tr.querySelector('[name=mode]').value,advance:tr.querySelector('[name=advance]').checked,categories:[...tr.querySelectorAll('[data-category]:checked')].map(el=>el.dataset.category)};
}
function human(v){if(v===undefined)return '(unset)';if(v===null)return '(none)';if(typeof v==='string')return v.length>140?v.slice(0,137)+'…':v;if(Array.isArray(v)){if(!v.length)return '(none)';if(v.every(x=>typeof x!=='object'))return v.join(', ');if(v.every(x=>x?.denomination))return v.map(x=>`${x.custom?.enabled?x.custom.formula:x.number+'d'+x.denomination+(x.bonus?' '+x.bonus:'')} ${(x.types ?? []).join('/')}`).join('; ');if(v.every(x=>x?.value!==undefined))return v.map(x=>`${x.label || x.key || ''}: ${x.value}`).join('; ').slice(0,180);return `${v.length} entries`;}if(typeof v==='object')return Object.entries(v).map(([k,x])=>`${k}: ${typeof x==='object'?'…':x}`).join(', ').slice(0,160);return String(v);}
function changeLabel(path){const names={'system.attributes.hp.value':'Current HP','system.attributes.hp.max':'Maximum HP','system.attributes.ac.flat':'Armor Class','system.attributes.movement.walk':'Walking speed',name:'Name',img:'Portrait',folder:'Folder'};if(names[path])return names[path];const m=path.match(/^system\.abilities\.(str|dex|con|int|wis|cha)\.value$/);if(m)return {str:'Strength',dex:'Dexterity',con:'Constitution',int:'Intelligence',wis:'Wisdom',cha:'Charisma'}[m[1]];return path.replace(/system\.activities\.[^.]+\.damage\.parts/,'Damage').replace(/system\.description\.value/,'Description').replace(`flags.${ID}.key`,'Workbook Actor Key');}
function changeHTML(result,{editable=true}={}){
 const decisions=(result.decisions ?? []).map(c=>`<div class="conflict-choice"><strong>${esc(changeLabel(c.path))}</strong><small>Current: ${esc(human(c.before))}<br>Workbook: ${esc(human(c.after))}</small>${editable ? `<label>Resolve this conflict<select data-conflict-choice="${esc(c.key)}"><option value="keep" ${c.resolution==='keep'?'selected':''}>Keep current value</option><option value="incoming" ${c.resolution==='incoming'?'selected':''}>Use workbook value</option></select></label>` : `<p>${c.resolution==='incoming'?'Use workbook value':'Keep current value'}</p>`}</div>`).join('');
 return `<div class="change-list">${result.changes.map(c=>`<p><strong>${esc(changeLabel(c.path))}</strong><br>${esc(human(c.before))} → ${esc(human(c.after))}</p>`).join('') || '<p>No supplied actor values need changing.</p>'}${decisions}${result.conflicts.map(c=>`<p class="warning">${esc(c)}</p>`).join('')}</div>`;
}
async function preview(plans,scope){
 const folders='<option value="">No folder</option>'+scope.list('Folder').filter(f=>f.type==='Actor').map(f=>`<option value="${f.id}">${esc(folderLabel(f,scope.list('Folder')))}</option>`).join('');
 const content=`<div class="sbs-forge"><h2>⚒ Actor Forge</h2><p><strong>${esc(scope.destinationLabel)}</strong></p>${scope.destination.actorPack?'<p>Advancements are retained for use in the World. Private notes stay in GM journals in this world.</p>':''}<p>Choose actors and destinations, then review the actual changes. Merge preserves edits made after a tracked import. Replace Forge content keeps other inventory. Whole replacement is also available.</p><div class="scroll"><table><thead><tr><th>Use / Actor</th><th>Destination & overrides</th><th>Validation & changes</th></tr></thead><tbody>${plans.map((p,i)=>`<tr data-row="${i}"><td><label><input type="checkbox" name="use" ${p.selected?'checked':''} ${p.errors.length?'disabled':''}> Import this actor</label><input name="name" value="${esc(p.data.name)}"><select name="type">${['character','npc','vehicle','group'].map(t=>`<option ${t===p.data.type?'selected':''}>${t}</option>`).join('')}</select><small>${esc(p.key)} · ${p.data.items?.length ?? 0} items</small><label><input name="advance" type="checkbox" ${p.advance?'checked':''} ${scope.destination.actorPack?'disabled':''}> Apply unconfigured advancements</label><details><summary>Content to update</summary>${CATEGORIES.map(k=>`<label><input type="checkbox" data-category="${k}" ${p.categories.includes(k) && !(k==='permissions' && p.target && !p.ownership) ? 'checked' : ''}> ${CATEGORY_NAMES[k]}</label>`).join('')}</details></td><td><label>Import destination<select name="target">${updateChoices(p,scope)}</select></label><label>Update mode<select name="mode">${Object.entries(MODES).map(([k,label])=>`<option value="${k}" ${k===p.mode?'selected':''}>${esc(label)}</option>`).join('')}</select></label><label>Portrait<div class="portrait-control"><img class="portrait-preview" data-portrait-preview src="${esc(p.data.img)}" alt="Actor portrait"><input name="image" value="${esc(p.data.img)}"><button type="button" data-pick-portrait>Browse / Upload</button></div></label><label>Existing folder<select name="folder">${folders}</select></label><label>New folder path<input name="folderPath" placeholder="SBS Test / Couriers"></label><small>A new path takes priority over the existing folder selection. Missing Actor folders are created during import.</small>${permissionControls(p)}<button type="button" data-save-preset>Save these settings as preset</button></td><td><div class="error">${p.errors.map(esc).join('<br>')}</div><div class="warning">${p.warnings.map(esc).join('<br>')}</div><small>${p.relations.length} actor links · ${p.gmDetails.length} GM notes</small><details><summary>Changes</summary><div data-diff></div></details></td></tr>`).join('')}</tbody></table></div></div>`;
 const selected=await D().wait({window:{title:'Actor Forge — Preview'},position:{width:1100},content,render:(_e,d)=>{
  for(const tr of d.element.querySelectorAll('[data-row]')){const p=plans[Number(tr.dataset.row)];let folder;try{folder=findActorFolder(p.folderPath ?? (p.folder || p.data.folder),scope);}catch(err){p.warnings.push(err.message);}if(folder)tr.querySelector('[name=folder]').value=folder.id;else tr.querySelector('[name=folderPath]').value=p.folderPath ?? p.folder ?? '';
   tr.querySelector('[data-save-preset]').addEventListener('click',async e=>{e.preventDefault();try{await saveRowPreset(readRow(tr,p),scope);}catch(err){await report('Preset',err.message);}});
   tr.querySelector('[data-pick-portrait]').addEventListener('click',async e=>{e.preventDefault();try{await pickPortrait(tr.querySelector('[name=image]'),CONFIG.ux?.FilePicker ?? foundry.applications.apps?.FilePicker ?? globalThis.FilePicker);}catch(err){await report('Portrait Picker',err.message);}});
   const redraw=()=>{try{const next=readRow(tr,p);p.conflictChoices=next.conflictChoices;tr.querySelector('[data-portrait-preview]').src=next.data.img;tr.querySelector('[data-diff]').innerHTML=changeHTML(previewUpdate(next,scope));}catch(err){tr.querySelector('[data-diff]').innerHTML=`<p class="error">${esc(err.message)}</p>`;}};
   tr.addEventListener('change',redraw);tr.querySelector('[name=target]').addEventListener('change',()=>{tr.querySelector('[data-category=permissions]').checked=false;p.conflictChoices={};tr.querySelector('[data-diff]').innerHTML='';redraw();});
   for(const el of tr.querySelectorAll('[data-access-user],[name=access-default]'))el.addEventListener('change',()=>{tr.querySelector('[data-category=permissions]').checked=true;redraw();});redraw();
  }
 },buttons:[{action:'review',label:'Review Selected',default:true,callback:(_e,_b,d)=>[...d.element.querySelectorAll('[data-row]')].filter(tr=>tr.querySelector('[name=use]').checked && !plans[Number(tr.dataset.row)].errors.length).map(tr=>readRow(tr,plans[Number(tr.dataset.row)]))},{action:'cancel',label:'Cancel'}]});if(!Array.isArray(selected)||!selected.length)return;
 await scope.refresh();validateImport(selected,scope);
 const reviews=selected.map(p=>{const result=previewUpdate(p,scope);p.reviewExpected=result.expected;return `<h3>${esc(p.data.name)} — ${p.target?esc(MODES[p.mode]):'New actor'}</h3>${changeHTML(result,{editable:false})}<p>${p.relations.length} relationship rows · ${p.gmDetails.length} GM notes · ${p.advance?'Advancement choices will open':'Advancements retained without applying'}</p>`;});
 const confirmed=await D().confirm({window:{title:'Actor Forge — Confirm Changes'},position:{width:850},content:`<div class="sbs-forge"><p><strong>${esc(scope.destinationLabel)}</strong></p><div class="scroll">${reviews.join('<hr>')}</div><p>Import ${selected.length} actor(s)? This becomes the new Undo Last Import batch.</p></div>`});if(!confirmed)return;
 ui.notifications.info('Actor Forge is importing. Complete any advancement choices that open.');
 await scope.refresh();const result=await importPlans(selected,scope);await report('Actor Forge — Results',result.lines.join('\n'));
}
async function sourcePicker(scope,preset){
 scope ??=await destinationEnvironment(env());
 if(!sourceRecords.length)return report('Sources','Load 5e.tools source files first.');
 const picked=await D().wait({window:{title:'Actor Forge — Source Library'},position:{width:900},content:`<div class="sbs-forge"><p><strong>${esc(scope.destinationLabel)}</strong></p><p>Pick creatures to create as NPCs, or items to place on a character. Species/background/class choices can use native advancements. Review all conversion notes.</p><label>Item destination<select name="target"><option value="">Create a new character</option>${scope.list('Actor').filter(a=>['character','npc'].includes(a.type)).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>New character name<input name="name" value="Source Test Character"></label><label>Class level<input name="level" type="number" min="1" max="20" value="1"></label><label><input name="advance" type="checkbox" ${scope.destination.actorPack?'disabled':'checked'}> Apply unconfigured advancements</label><input name="search" type="search" placeholder="Filter by name, type or source"><div class="scroll">${sourceRecords.map((r,i)=>`<label class="source-record" data-source="${i}" data-search="${esc((r.name+' '+r.kind+' '+r.source+' '+(r.context || '')).toLowerCase())}"><input type="checkbox" value="${i}"> <strong>${esc(r.name)}</strong> · ${esc(r.kind)} · ${esc(r.source)}${r.context?' · '+esc(r.context):''}${r.warnings.length?`<small class="warning">${r.warnings.map(esc).join('; ')}</small>`:''}</label>`).join('')}</div></div>`,render:(_e,d)=>{d.element.querySelector('[name=search]').addEventListener('input',e=>{for(const row of d.element.querySelectorAll('[data-source]'))row.hidden=!row.dataset.search.includes(e.target.value.toLowerCase());});},buttons:[{action:'choose',label:'Validate & Preview',default:true,callback:(_e,_b,d)=>({records:[...d.element.querySelectorAll('[data-source] input:checked')].map(el=>sourceRecords[Number(el.value)]),target:d.element.querySelector('[name=target]').value,name:d.element.querySelector('[name=name]').value,level:Number(d.element.querySelector('[name=level]').value),advance:d.element.querySelector('[name=advance]').checked})}]});if(!picked?.records.length)return;
 const plans=picked.records.filter(r=>r.kind==='monster').map(r=>blankPlan(r.key,r.data,{warnings:[...r.warnings]}));const items=picked.records.filter(r=>r.kind!=='monster');
 if(items.length){const old=picked.target?scope.get('Actor',picked.target):null;const p=blankPlan('source-character-'+(old?.id || foundry.utils.randomID()),{name:old?.name || picked.name,img:old?.img || 'icons/svg/mystery-man.svg',type:old?.type || 'character',system:{},items:items.map(r=>{const d=clone(r.data);if(d.type==='class')d.system.levels=picked.level;return d;})},{target:old?.id || '',folder:old?.folder?.id || '',advance:picked.advance,warnings:items.flatMap(r=>r.warnings.map(w=>`${r.name}: ${w}`))});if(old){p.data.flags ??={};p.data.flags[ID]={key:old.flags?.[ID]?.key || p.key};p.categories=p.categories.filter(k=>k!=='permissions');}plans.push(p);}
 for(const p of plans)p.catalog=catalogRows(sourceRecords);if(preset)applyPreset(plans,preset,game.users);await preparePlans(plans,scope,sourceRecords);await preview(plans,scope);
}
function preferenceUI(){return {Dialog:D(),env,users:game.users,report,destinationControls,readDestination,permissionControls,categoryNames:CATEGORY_NAMES};}
function saveRowPreset(plan,scope){return saveRowPresetUI(plan,{...scope,libraryIds:[...loadedLibraryIds]},preferenceUI());}
async function presets(){return managePresets(preferenceUI());}
async function sources(){
 gm();const store=readPreferences(env(),'libraries');
 const value=d=>({files:[...d.element.querySelector('[name=files]').files],library:d.element.querySelector('[name=library]').value,name:d.element.querySelector('[name=libraryName]').value,destination:readDestination(d.element)});
 const choice=await D().wait({window:{title:'Actor Forge — Load 5e.tools Sources'},position:{width:720},content:`<div class="sbs-forge"><p>Load source files once, save them under a name, and reuse them after a refresh. Libraries are kept in GM-only journals in this world.</p><label>Saved library<select name="library"><option value="">Use loaded sources only</option>${store.entries.map(l=>`<option value="${esc(l.id)}">${esc(l.name)} · ${l.recordCount} records</option>`).join('')}</select></label><label>New source files<input name="files" type="file" accept=".json" multiple></label><label>Library name<input name="libraryName" placeholder="My homebrew sources" maxlength="100"></label>${destinationControls()}<p>${sourceRecords.length} records loaded this session.</p></div>`,buttons:[
 {action:'load',label:'Load & Choose',default:true,callback:(_e,_b,d)=>({action:'load',...value(d)})},
 {action:'save',label:'Save New Library',callback:(_e,_b,d)=>({action:'save',...value(d)})},
 {action:'replace',label:'Replace Selected Library',callback:(_e,_b,d)=>({action:'replace',...value(d)})},
 {action:'clear',label:'Clear Loaded',callback:()=>({action:'clear'})},
 {action:'delete',label:'Delete Selected Library',callback:(_e,_b,d)=>({action:'delete',...value(d)})}]});
 if(!choice)return;
 if(choice.action==='clear'){sourceBundles.clear();sourceRecords=[];loadedLibraryIds.clear();return report('Loaded Sources Cleared','Saved libraries remain available. Reopen Sources & Libraries to load another set.');}
 const selected=store.entries.find(l=>l.id===choice.library);
 if(choice.library && !selected)throw Error('The selected library is missing. Reopen the list.');
 if(choice.action==='delete'){
  if(!selected)throw Error('Select a library to delete');
  if(await D().confirm({window:{title:'Delete source library?'},content:`<p>Delete ${esc(selected.name)}? Already imported actors keep their content. Clear Loaded to unload this session’s copy.</p>`})){await deletePreference(env(),'libraries',selected.id,store.revision);loadedLibraryIds.delete(selected.id);}return;
 }
 const warnings=await loadSources(choice.files ?? []);
 if(choice.action==='save' || choice.action==='replace'){
  if(choice.action==='replace' && !selected)throw Error('Select a library to replace');
  if(choice.action==='replace' && !await D().confirm({window:{title:'Replace source library?'},content:`<p>Replace ${esc(selected.name)} with all currently loaded sources?</p>`}))return;
  const saved=await saveSourceLibrary(env(),choice.name || selected?.name,sourceBundles,{id:choice.action==='replace'?selected.id:undefined,revision:store.revision});loadedLibraryIds.add(saved.id);
  return report('Source Library Saved',`${saved.name}: ${saved.recordCount} records. It is available in Import and Sources & Libraries after refresh.`);
 }
 if(selected)warnings.push(...loadLibraries([selected.id]));
 if(warnings.length)await report('Source File Notes',warnings.join('\n'));
 const scope=await destinationEnvironment(env(),choice.destination);scope.libraryIds=[...loadedLibraryIds];await sourcePicker(scope);
}
async function undo(){gm();const log=await readUndo(env());if(!log?.entries?.length)return report('Undo','No import to undo.');if(!await D().confirm({window:{title:'Undo last import?'},content:'<p>Restore updated actors and delete newly created documents from the last batch. Edited actors and their linked new members will be preserved.</p>'}))return;const r=await undoImport(env());await report('Undo Results',r.lines.join('\n'));}
async function exportActors(){
 gm();const actors=[...game.actors];const picked=await D().wait({window:{title:'Actor Forge — Export'},position:{width:720},content:`<div class="sbs-forge"><p>Select any combination of actors. Native data, items, effects and relationships are preserved. Large actor data is split automatically across workbook cells.</p><label>Filename<input name="filename" value="Actor_Forge_Export"></label><label><input name="private" type="checkbox"> Include GM notes in this downloadable workbook</label><label>Type filter<select name="type"><option value="">All types</option>${['character','npc','vehicle','group'].map(t=>`<option>${t}</option>`).join('')}</select></label><label>Folder filter<select name="folder"><option value="">All folders</option>${game.folders.filter(f=>f.type==='Actor').map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select></label><button type="button" data-select>Select visible</button><button type="button" data-clear>Clear all</button><div class="scroll">${actors.map(a=>`<label data-actor="${a.id}" data-type="${a.type}" data-folder="${a.folder?.id ?? ''}" style="display:block"><input type="checkbox" value="${a.id}">${esc(a.name)} (${a.type}) — ${esc(a.folder?.name ?? 'No folder')}</label>`).join('')}</div></div>`,render:(_e,d)=>{const el=d.element;const filter=()=>{for(const r of el.querySelectorAll('[data-actor]'))r.hidden=!!((el.querySelector('[name=type]').value&&r.dataset.type!==el.querySelector('[name=type]').value)||(el.querySelector('[name=folder]').value&&r.dataset.folder!==el.querySelector('[name=folder]').value));};el.querySelector('[name=type]').onchange=filter;el.querySelector('[name=folder]').onchange=filter;el.querySelector('[data-select]').onclick=()=>el.querySelectorAll('[data-actor]').forEach(r=>{if(!r.hidden)r.querySelector('input').checked=true;});el.querySelector('[data-clear]').onclick=()=>el.querySelectorAll('[data-actor] input').forEach(r=>r.checked=false);},buttons:[{action:'export',label:'Download Workbook',default:true,callback:(_e,_b,d)=>({actors:[...d.element.querySelectorAll('[data-actor] input:checked')].map(x=>game.actors.get(x.value)),name:d.element.querySelector('[name=filename]').value,private:d.element.querySelector('[name=private]').checked})}]});if(!picked?.actors?.length)return;
 const privateDetails=picked.private?Object.fromEntries(picked.actors.map(a=>[a.id,readPrivateDetails(env(),actorRecordKey(a))])):{};
 const book=makeBook(XLSX,exportRows(picked.actors,{privateDetails,folders:[...game.folders]}));download(XLSX.write(book,{bookType:'xlsx',type:'array'}),(picked.name.replace(/[^\w.-]/g,'_') || 'Actor_Forge_Export')+'.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
}
function attachBiography(app,html){
 return mountBiography(app,html,env(),{onError:err=>report('SBS Details',err.message),onAdvancements:async actor=>{const warnings=await runNativeAdvancements(actor);if(warnings.length)await report('Advancements',warnings.join('\n'));}});
}
async function details(actor){
 const a=actor?.documentName==='Actor' ? actor : canvas.tokens?.controlled[0]?.actor ?? game.actors.get(game.user.character?.id);
 if(!a)return ui.notifications.warn('Select a token or assign a character to open its Biography.');
 return openBiography(a,{user:game.user,mount:attachBiography,onWarning:text=>ui.notifications.warn(text)});
}
async function open(){
 gm();if(busy)return ui.notifications.warn('Actor Forge is already working.');
 const action=await D().wait({window:{title:'SaltyBananaSlug’s Actor Forge'},position:{width:900},content:`<div class="sbs-forge"><h2><img class="forge-brand" src="modules/sbs-actor-forge/assets/forge.svg" alt="SaltyBananaSlug Actor Forge"> Actor Forge · ${BUILD}</h2><p>Import actors, review selective updates, connect their party and vehicles, and keep your GM notes close.</p><p>Foundry 13 · D&D5e 5.x</p></div>`,buttons:[{action:'import',label:'Import',default:true},{action:'sources',label:'Sources & Libraries'},{action:'presets',label:'Presets'},{action:'export',label:'Export'},{action:'details',label:'Biography'},{action:'undo',label:'Undo Last Import'},{action:'test',label:'Compatibility Check'}]});
 try{busy=true;if(action==='import')await importFile();if(action==='sources')await sources();if(action==='presets')await presets();if(action==='export')await exportActors();if(action==='undo')await undo();if(action==='details')await details();if(action==='test')await report('Actor Forge — Compatibility Check',(await runCompatibilityChecks(env())).join('\n'));}catch(e){console.error(ID,e);await report('Actor Forge — Error',e.message);}finally{busy=false;}
}
Hooks.once('init',()=>{game.settings.register(ID,'undo',{scope:'world',config:false,type:Object,default:{entries:[]}});game.settings.registerMenu(ID,'launcher',{name:'Actor Forge',label:'Open Actor Forge',hint:'Import, source libraries, presets, export, Biography notes, undo and compatibility checks.',icon:'fas fa-hammer',restricted:true,type:class extends foundry.appv1.api.FormApplication{render(){open();return this;}}});});
Hooks.once('ready',async()=>{game.modules.get(ID).api={open,details,ensureLauncher:()=>ensureLauncher(game,Macro),runCompatibilityChecks:()=>runCompatibilityChecks(env()),registerSheetAdapter};if(game.system.id!=='dnd5e')return;try{await ensureLauncher(game,Macro);}catch(e){console.error(ID,e);ui.notifications.warn('Actor Forge could not create its macro. Open it through Module Settings.');}if(ui.settings?.element)addSettingsLauncher(ui.settings,ui.settings.element,game,open,document);console.info(`SaltyBananaSlug Actor Forge ${BUILD} ready`);});
Hooks.on('renderSettings',(app,html)=>addSettingsLauncher(app,html,game,open,document));
Hooks.on('renderActorSheet',attachBiography);
Hooks.on('renderActorSheetV2',attachBiography);
Hooks.on('renderApplicationV2',(app,html)=>{if((app.actor ?? app.document)?.documentName==='Actor')attachBiography(app,html);});
